// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xsg6ZpFiMGveeUyljHkuRNsOKSKGt5E',
    appId: '1:725666963121:android:8ea4bd7bcb3516d48d0c90',
    messagingSenderId: '725666963121',
    projectId: 'email-7d3ce',
    storageBucket: 'email-7d3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXxyqEhK6Gx4NHGj3-L50GSGTPycaahBk',
    appId: '1:725666963121:ios:9c389734c49d81828d0c90',
    messagingSenderId: '725666963121',
    projectId: 'email-7d3ce',
    storageBucket: 'email-7d3ce.appspot.com',
    androidClientId: '725666963121-38sfsi183o3vrhgojvce1s271bi3n1ee.apps.googleusercontent.com',
    iosClientId: '725666963121-evam8pgrn39g3dq2kjle5akf1jkbeuqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikumrev3',
  );
}
